### ISSUE TITLE
Backend project setup

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/studypal#10]
## Tasks
- [ ] Work on directory structure
- [ ] Setup DB integration
- [ ] Setup Logging class
- [ ] Setup Exceptions class
- [ ] Configure application

## Notes
- Django is to be used for the backend

**Comment by fracergu** [comment]
I have made an approximation of the backend implementation, can you assign me the issue to open a PR?

**Comment by Shobayosamuel** [comment]
you made a typo in the requirements.txt file name
