### ISSUE TITLE
User onboarding

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/studypal#11]
## Tasks
- [ ] Create user model
- [ ] Create registration endpoint
- [ ] Create login endpoint
