### ISSUE TITLE
Study plan API

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/studypal#13]
# User story
As a student, I want StudyPal to create a study plan that fits my study goals and time availability.

## Tasks
- [ ] Create endpoint create study goals
- [ ] Create an endpoint to delete study goals
- [ ] Create an endpoint to update study goals
- [ ] Study plan update API
      - Details
          - The days of the week they are available for studying.
          - Preferred study times (morning, afternoon, evening).
          - Maximum study session duration (e.g., 1 hour, 2 hours).
          - How frequently they can study (e.g., daily, every other day, weekends)?
          - Context: For example, if a user is preparing for a competitive exam, they might mention their current level of knowledge in the subject.

## Notes
- Ensure

**Comment by festuscharles** [comment]
🤔

**Comment by VidyaYadavv1519** [comment]
hiiii, is this issue still available
can you assign me ??

**Comment by devvspaces** [comment]
Yes it's available
