### ISSUE TITLE
Setup study plan

### ISSUE THREAD

**Issue by devvspaces** [devvspaces/studypal#20]
# User story
As a student, I want StudyPal to create a study plan that fits my study goals and time availability.

## Tasks
- [ ] Create a Study planner page
- [ ] Option to add new goals
- [ ] Option to update study preferences
- [ ] Button to generate a study plan
- [ ] Button to review study plan

## Notes
- If the study plan is being generated, the user should not be able to update the study plan until it's done
- Create a way to ensure the user knows that the plan is being generated
- When the plan is completely generated, show a button for the user to review the plan

**Comment by SathvikKandadi** [comment]
Hey I am interested in working on this and I am new to OpenSource can you assign this issue to me?

**Comment by devvspaces** [comment]
Yes
